export enum especialite {
  PEDIATRIE = 'PEDIATRIE',

  NEANTOLOGIE = 'NEANTOLOGIE',

  NEUROLOGIE = 'NEUROLOGIE',

  OPHTALMOLOGIE = 'OPHTALMOLOGIE',

  MEDECINE_INTERNE = 'MEDECINE_INTERNE',

  ORTHOPEDIE = 'ORTHOPEDIE',

  CARDIOLOGIE = 'CARDIOLOGIE',

  GENETIQUE = 'GENETIQUE',

  GYNECOLOGIE = 'GYNECOLOGIE',

  AUTRE = 'AUTRE',
}
